[package]
name = "simple_assembler"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
nom = "7.1.3"
log = "0.4.22"
pretty_env_logger = "0.5.0"
thiserror = "2.0.9"
anyhow = "1.0.95"
num = "0.4.3"