[package]
name = "SimpleAssembler"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"
serde = { version = "1.0.215", features = ["derive"] }
nom = "7.1.3"
clap = { version = "4.5.23", features = ["derive"] }
anyhow = "1.0.94"